### ISSUE TITLE
integrate workflow into CLDF's CLI

### ISSUE THREAD

**Issue by martino-vic** [LoanpyDataHub/loanpy#46]
Currently loanpy does the file reading on its own with `etym_obj = Etym(forms_csv="forms.csv", source_language="English", target_language="Bislama")` but this could be handled with sth like: 

```Python
from cldfbench_tryonbislama import Dataset as BSLM
bslm = BSLM()
ds = Dataset.from_metadata(bslm.cldf_dir.joinpath("cldf-metadata.json"))
for val in ds.objects("FormTable"):
    # execute loanpy workflow

```

**Comment by xrotwang** [comment]
You don't need any of the `cldfbench` stuff here, I think. Plain `pycldf` should be enough:
```python
>>> from pycldf import Dataset
>>> ds = Dataset.from_metadata("PATH/TO/cldf-metadata.json")
```

This may be different if you want to add a CLI to `loanpy`, in particular if the cli needs access to Glottolog or Concepticon data. If that's the case, you could implement the cli as [cldfbench plugin](https://github.com/cldf/cldfbench/blob/master/src/cldfbench/commands/README.md).

**Comment by martino-vic** [comment]
Integrated the loanpy workflow as tightly as possible into the CLDF repository architecture, applying changes mostly through the lexibank-script, and sometimes through the CLI, where not otherwise possible: [ronataswestoldturkic](https://github.com/LoanpyDataHub/ronataswestoldturkic), [gerstnerhungarian](https://github.com/LoanpyDataHub/gerstnerhungarian), and [koeblergothic](https://github.com/LoanpyDataHub/koeblergothic)
